version: "3"

services:

  db:
    container_name: transcendence_db
    image: postgres:17-alpine
    env_file:
      - db/.env
    volumes:
      - ./db/postgres:/var/lib/postgresql/data

  redis:
    container_name: transcendence_redis
    image: redis:alpine

  backend:
    container_name: django_app
    image: transcendence_backend
    command: ./wait_db.sh uvicorn TranscendenceBackend.asgi:application --host 0.0.0.0 --port 8000
    build:
      context: backend
    env_file:
      - backend/.env
    volumes:
      - ./avatars:/app/media/avatars
    depends_on:
      - db
      - redis

  nginx:
    image: nginx:latest
    container_name: nginx
    build:
      context: nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./frontend:/usr/share/nginx/html
      - ./avatars:/usr/share/nginx/avatars
      - ./certs:/etc/ssl/certs
    ports:
      - "8443:8443"
    entrypoint: ["/bin/sh", "-c", "/etc/ssl/certs/generate_cert.sh && nginx -g 'daemon off;'"]
    depends_on:
      - backend