version: "3"

services:

  db:
    container_name: transcendence_db
    image: postgres:17-alpine
    # ports:
    #   - "5432:5432"
    env_file:
      - db/.env
    # volumes:
    #   - ./db/postgres:/var/lib/postgresql/data

  redis:
    container_name: transcendence_redis
    image: redis:alpine
    ports:
      - "6379:6379"

  backend:
    container_name: django_app
    environment:
      - REDIS_HOST=transcendence_redis
      - REDIS_PORT=6379
    image: transcendence_backend
    command: ./wait_db.sh uvicorn TranscendenceBackend.asgi:application --host 0.0.0.0 --port 8000
    build:
      context: backend
    ports:
      - "8000:8000"
    env_file:
      - backend/.env
    depends_on:
      - db
      - redis
    volumes:
      - ./avatars:/app/media/avatars

  nginx:
    image: nginx:latest
    container_name: nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./frontend:/usr/share/nginx/html
      - ./avatars:/usr/share/nginx/avatars
    ports:
      - "8080:8080"
    depends_on:
      - backend
