version: "3"

services:

  db:
    container_name: transcendence_db
    image: postgres:17-alpine
    ports:
      - "5432:5432"
    env_file:
      - db/.env
    # volumes:
    #   - ./db/postgres:/var/lib/postgresql/data

  redis:
    container_name: transcendence_redis
    image: redis:alpine

  backend:
    container_name: django_app
    image: transcendence_backend
    # command: ./wait_db.sh python manage.py runserver 0.0.0.0:8000
    command: ./wait_db.sh uvicorn TranscendenceBackend.asgi:application --host 0.0.0.0 --port 8000
    build:
      context: backend
    ports:
      - "8000:8000"
    env_file:
      - backend/.env
    depends_on:
      - db
      - redis
