# Generated by Django 5.1.3 on 2025-01-13 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0002_game_status_game_winning_score_alter_game_player2'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='modified_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
