# Generated by Django 5.1.3 on 2025-07-30 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_userprofile_is_2fa_enabled_userprofile_otp_secret'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='language',
            field=models.CharField(choices=[('en', 'English'), ('it', 'Italian'), ('ru', 'Russian')], default='en', max_length=10),
        ),
    ]
